language:
- node_js
node_js:
- '0.12'
branches:
  only:
  - master
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
- npm install
- npm install -g bower
- npm install -g gulp
- bower install
script: gulp